version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - '3000:3000'
    volumes:
      - /app/node_modules # this syntax will not reference this folder to host folder
      - .:/app